remote_theme: just-the-docs/just-the-docs@v0.4.0.rc3
title: Speed comparison
description: Check out the speed comparison results!
exclude:
  - "templates"

color_scheme: dark

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
