remote_theme: just-the-docs/just-the-docs@v0.4.0.rc3
title: Speed comparison
description: A speed comparison of various programming languages.
url: "https://niklas-heer.github.io" # the base hostname & protocol for your site, e.g. http://example.c

exclude:
  - templates/

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

# Aux links for the upper right navigation
aux_links:
  "Speed comparison on GitHub":
    - "//github.com/niklas-heer/speed-comparison"

color_scheme: dark

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
